export const FETCH_EMPLOYEELIST_REQUEST = 'FETCH_EMPLOYEELIST_REQUEST';
export const FETCH_EMPLOYEELIST_SUCCESS = 'FETCH_EMPLOYEELIST_SUCCESS';
export const FETCH_EMPLOYEELIST_FAILURE = 'FETCH_EMPLOYEELIST_FAILURE';

export const EDITEMPLOYEE_REQUEST = 'EDITEMPLOYEE_REQUEST';
export const EDITEMPLOYEE_SUCCESS = 'EDITEMPLOYEE_SUCCESS';
export const EDITEMPLOYEE_FAILURE = 'EDITEMPLOYEE_FAILURE';